version: '3'
services:
  softethervpn:
    image: toprock/softether
    restart: always
    ports:
      - 443:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - softether_data:/mnt
volumes:
  softether_data: